### ISSUE TITLE
Backport of #917 for Wry 0.24

### ISSUE THREAD

**Issue by Kijewski** [tauri-apps/wry#1000]
#917 fixes a one letter typo in a function that is used during the start up of Wry on Android systems. The bug fix is part of Wry since in the 0.31 release, but was not backported to other branches. The current stable branch of Tauri, 1.4, still uses Wry 0.24, so the bug is present for up-to-date users unless you want to use an alpha version.

It would be nice if you could release a v0.24.4 of Wry. With the fix Tauri runs fine on Android, but without it it crashes immediately.

**Comment by amrbashir** [comment]
Tauri 1.4 doesn't support mobile development at all so the backport won't be necessary.

**Comment by Kijewski** [comment]
Too bad, because I can assure you that your tools (`cargo tauri android build --apk`) are already able to build working `.apk`s for tauri apps, even if you did not intent them to. :) Thank you for all your hard work anyway!

**Comment by FabianLars** [comment]
Then you're using Tauri v2 since that command is not (and wasn't ever) part of the v1 cli.

**Comment by Kijewski** [comment]
I installed the cli from its git head, but project source uses the stable tauri version:

```toml

[workspace.dependencies]
tauri = { version = "1.4", default-features = false, features = ["compression", "custom-protocol", "objc-exception", "wry"] }
tauri-build = "1.4"
wry = { version = "0.24", default-features = false, features = ["linux-headers", "objc-exception", "protocol"] }

[patch.crates-io]
wry = { git = "https://github.com/Kijewski/wry.git", branch = "fix/android/url" }
```
